---
version: '3.7'

services:

    database:
        healthcheck:
            test: "export MYSQL_PWD='cwCvv3sjRHjP^2U_'; mysqladmin -P 3603 --user=root --silent ping"
            start_period: 1m
            interval: 60s
            timeout: 5s
            retries: 3

    webserver:
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:7080"]
            start_period: 1m
            interval: 30s
            timeout: 5s
            retries: 3

    site:
        environment:
            APP_ENV: production
        healthcheck:
            test: ["CMD-SHELL", "SCRIPT_NAME=/fpm-ping SCRIPT_FILENAME=/fpm-ping REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1"]
            start_period: 1m
            interval: 30s
            timeout: 5s
            retries: 3

    admin:
        environment:
            APP_ENV: production
        healthcheck:
            test: ["CMD-SHELL", "SCRIPT_NAME=/fpm-ping SCRIPT_FILENAME=/fpm-ping REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1"]
            start_period: 1m
            interval: 30s
            timeout: 5s
            retries: 3
