---
version: '3.7'

volumes:
    local_app:
        driver: local
        driver_opts:
            type: none
            device: $PWD/../${LOCAL_APP_PATH}
            o: bind

services:

    webserver:
        volumes:
            # - type: bind
            #   source: ./nginx/docker-entrypoint.sh
            #   target: /entrypoint.sh
            #   read_only: true
            - type: volume
              source: local_app
              target: ${REMOTE_SRC}

    app:
        volumes:
            - ./../${LOCAL_APP_PATH}:${REMOTE_SRC}:delegated
            - ./php/docker-entrypoint.sh:/entrypoint.sh:ro
            - ./php/configs/php-local.ini:/usr/local/etc/php/php.ini:ro
            # - ./php/configs/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro

    queue:
        volumes:
            - ./../${LOCAL_APP_PATH}:${REMOTE_SRC}:delegated

    scheduler:
        volumes:
            - ./../${LOCAL_APP_PATH}:${REMOTE_SRC}:delegated
